import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  // console.log(props)
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Bienvenue sur code.io</h1>
        <h3>Le blog communautaire du développement web</h3>
        <div class="card" style={{ width: "25rem" }}>
          <div class="card-body">
            <h5 class="card-title">Lisez les acticles</h5>
            <p class="card-text">
              Maximisez votre culture web <br /> Chaque auteur tente de vous
              apporter le plus de valeur possible par article.
            </p>
            <Link href={"/blog"}>Visitez le blog</Link>
          </div>
        </div>

        <div class="card" style={{ width: "25rem" }}>
          <div class="card-body">
            <h5 class="card-title">Faites un tour vers la liste des membres</h5>
            <p class="card-text">
              Faites vous des amis <br />
              Ajoutez, invitez et discuter avec les différents menbres.
            </p>
            <Link href="/blog">Visitez le blog</Link>
          </div>
        </div>
      </main>
    </>
  );
}
